name: Update Repository Links
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This ensures we have the full git history
          
      - uses: vixshan/linkapp@v1.1.5
        with:
          token: ${{ secrets.GH_TOKEN }}
          config-path: '.github/updatelinks.yml'  # Explicitly set the config path
          create-pr: 'true'
